services:
  server:
    build:
      context: .

    volumes:
      - ./:/app
      - /app/node_modules

    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database

    command: npm run start:dev

    ports:
      - 3000:3000

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16.1-alpine3.19
    hostname: database
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
